name: Cache gh-lang-n-streak-stats Action
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours, change it accordingly

jobs:
  stats:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Stats Card
    steps:
      - uses: actions/checkout@v4
        name: Check out current commit
      - uses: suisei-cn/actions-download-file@v1.6.0
        id: stats
        name: Download the stats file
        with:
          url: "https://githubstats.johnsoftich.me/api/top-langs/?username=jsoftich&theme=dark&langs_count=10&exclude_repo=merlin-web&salt=1" # Put your own vercel instance URL here
          target: grs
          filename: lang-stats.svg # Need to have the file name prepared as svg
      - uses: suisei-cn/actions-download-file@v1.6.0
        id: streak
        name: Download the streak file
        with:
          url: "https://johnsoftich.com/apps/github-streak/?user=jsoftich&theme=dark&salt=1&exclude_days=Sun" # Put your own vercel instance URL here
          target: grs
          filename: streak-stats.svg # Need to have the file name prepared as svg          
      - uses: actions/upload-artifact@master
        with:
          name: stats
          path: grs
      - uses: actions/upload-artifact@master
        with:
          name: streak
          path: grs
  push:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push
    needs: [stats] # Put any jobs (card) needed here before we push
    steps:
      - uses: actions/download-artifact@master
        with:
          name: stats
          path: grs
      - uses: actions/download-artifact@master
        with:
          name: streak
          path: grs          
      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: resource/grs # May change to your desired branch name, the final URL need to be updated if you change this
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
