name: Cache gh-lang-n-streak-stats Action
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours, change it accordingly
jobs:
  stats:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Stats Card
    steps:
      - uses: actions/checkout@v5
        name: Check out current commit

      - name: Download the stats file
        run: |
          mkdir -p grs
          curl -fsSL -o grs/lang-stats.svg \
            "https://githubstats.johnsoftich.me/api/top-langs/?username=jsoftich&theme=dark&langs_count=10&exclude_repo=merlin-web;NFS-FloodTools-Site&salt=1&hide=xslt,html,batchfile,xBase"

      - name: Download the streak file
        run: |
          mkdir -p grs
          curl -fsSL -o grs/streak-stats.svg \
            "https://johnsoftich.com/apps/github-streak/?user=jsoftich&theme=dark&salt=1&exclude_days=Sun"

      - uses: actions/upload-artifact@v4
        with:
          name: stats
          path: grs/lang-stats.svg

      - uses: actions/upload-artifact@v4
        with:
          name: streak
          path: grs/streak-stats.svg

  push:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push
    needs: [stats] # Put any jobs (card) needed here before we push
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: stats
          path: grs

      - uses: actions/download-artifact@v4
        with:
          name: streak
          path: grs

      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: resource/grs # May change to your desired branch name, the final URL need to be updated if you change this
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
